name: wireless_quiz
description: wireless quiz client
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  responsive_sizer: ^3.1.0
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  wakelock: ^0.6.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/postImage.png
